name: iRaPCA
channels:
- rdkit
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - rdkit
    - pip
    - pip:
        - scikit-learn
        - xgboost==1.0.2
        - molvs
        - streamlit==1.5.0
        - mordred
        - matplotlib==3.3.2
        - plotly==5.0.0
        - validclust
