name: iRaPCA
channels:
- rdkit
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - rdkit
    - pandas==1.4.1
    - numpy==1.22.2
    - pip
    - pip:
        - scikit-learn
        - xgboost==1.0.2
        - molvs
        - streamlit==1.2.0
        - streamlit_tags
        - mordred
        - matplotlib==3.3.2
        - plotly==5.0.0
        - validclust
