name: iRaPCA
channels:
- rdkit
- conda-forge
- defaults
dependencies:
    - rdkit
    - pip
    - pip:
        - scikit-learn
        - molvs
        - streamlit==1.5.0
        - mordred
        - plotly
        - validclust
        - pandas==1.4.1
        - numpy==1.22.2
