name: iRaPCA
channels:
- conda-forge
- defaults
dependencies:
    - python==3.9.7
    - pandas==1.4.1
    - numpy==1.22.2
    - rdkit
    - pip
    - pip:
        - scikit-learn
        - molvs
        - streamlit==1.5.0
        - mordred
        - plotly
        - validclust

